### ISSUE TITLE
there's no such thing as an HTTP header that doesn't exist

### ISSUE THREAD

**Issue by kurisufriend** [Kami147/DismalSniper#1]
i don't know or care about what this is, but although the HTTP RFC includes some headers as part of the spec you can use the space for anything you want. curl a site behind cloudflare and check the response headers if you don't believe me.
after a cursory grep of the repo, i also can't find any use of nonstandard headers so i don't know where that came from regardless. the closes thing would be using a custom user-agent, which is actually technically what you're supposed to do spec-wise, though usually it's safer to spoof a common one.
looks to be shitcode anyway, so nice job owning them or whatever.

**Comment by Tenshi147** [comment]
The value of 'connection' was set to "open" when it is supposed to be "keep-alive"

**Comment by kurisufriend** [comment]
yeah, found it
